# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import api_pb2 as proto_dot_api__pb2


class TinyKafkaStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendMessage = channel.unary_unary(
        '/TinyKafka/SendMessage',
        request_serializer=proto_dot_api__pb2.SendMessageRequest.SerializeToString,
        response_deserializer=proto_dot_api__pb2.SendMessageResponse.FromString,
        )
    self.Watch = channel.unary_stream(
        '/TinyKafka/Watch',
        request_serializer=proto_dot_api__pb2.WatchRequest.SerializeToString,
        response_deserializer=proto_dot_api__pb2.WatchResponse.FromString,
        )


class TinyKafkaServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Watch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TinyKafkaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SendMessage,
          request_deserializer=proto_dot_api__pb2.SendMessageRequest.FromString,
          response_serializer=proto_dot_api__pb2.SendMessageResponse.SerializeToString,
      ),
      'Watch': grpc.unary_stream_rpc_method_handler(
          servicer.Watch,
          request_deserializer=proto_dot_api__pb2.WatchRequest.FromString,
          response_serializer=proto_dot_api__pb2.WatchResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TinyKafka', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
